services:
  nginx:
    container_name: silo-router-nginx
    ports:
      - "8080:8080"
    environment:
      - BACKEND_URL=http://target-server:3000
      - NGINX_PORT=8080
    depends_on:
      - go-server
    networks:
      - silo-network

networks:
  silo-network:
    driver: bridge
