log:
  level: debug
http:
  port: 8081
grpc:
  server_address: localhost:9090
  agent_id: agent-1
  tls:
    enabled: false
    cert_file: ./certs/agents/agent-1-cert.pem
    key_file: ./certs/agents/agent-1-key.pem
    ca_file: ./certs/ca/ca-cert.pem
    server_name_override: ""
local:
  service_url: http://localhost:3000
